### PR TITLE
go upgrade

### PR DESCRIPTION
**Pull request by pgvishnuram**
This change will upgrade go version to 1.17 including  golang docker build image and application base image .
Additionally running the service as non root.

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@abutaha - please if this PR is fine

**Comment by abutaha** [comment]
Thanks for the PR. Will review over the weekend.

**Comment by pgvishnuram** [comment]
@abutaha - any update on this PR

**Comment by pgvishnuram** [comment]
@abutaha - can we merge this

**Pull request closed without merging**
