### PR TITLE
Add IRSA support

### PR DESCRIPTION
**Pull request by dippynark**
Adds support for authenticating to STS using a Kubernetes signed JWT: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

### CODE REVIEW

**Comment by sc250024** [comment]
Any reason why this hasn't been merged?

**Comment by abutaha** [comment]
@sc250024 the only reason is just not enough time to check and test it. I will spare a few hours tomorrow to go through it and get it merged.

**Comment by abutaha** [comment]
Merged.

**Comment by sc250024** [comment]
Thank you @abutaha !

**Pull request merged**
