### PR TITLE
Switch to go mod

### PR DESCRIPTION
**Pull request by guusvw**
based on https://github.com/abutaha/aws-es-proxy/pull/52

### CODE REVIEW

**Comment by br00tal** [comment]
I would love to see this merged.

**Comment by br00tal** [comment]
So...any way to get this merged?

**Comment by asherf** [comment]
ping @abutaha

**Comment by abutaha** [comment]
Go mod has been added in branch v1.0-dev. I need to fix Kibana blank page issue in new versions before merging to master. If you can assist with that, I will be grateful.

**Pull request closed without merging**
