### PR TITLE
Add assume role support v2

### PR DESCRIPTION
**Pull request by ChristophP**
This is the exact same PR as https://github.com/abutaha/aws-es-proxy/pull/81 . Since the PR was stalled a bit because of merge conflicts we wanted to help out. Thanks to @joshgarnett for creating the the original PR.

### CODE REVIEW

**Comment by joshgarnett** [comment]
Thanks for tossing this together.

**Comment by ChristophP** [comment]
@joshgarnett No problem, our part was really easy after your work. Feel free to merge our changes back to your branch and have your PR merged instead of ours. It feels weird to take any credit for the work that mostly your did. 😅

**Comment by joshgarnett** [comment]
haha, I don't care about that.  Been slammed as well.  I'll just be happy to no longer keep making custom containers for our service.

**Comment by abutaha** [comment]
Thanks @ChristophP and @joshgarnett for your work on this.

I will have it merged tomorrow after I run a test on it.

**Comment by ChristophP** [comment]
@joshgarnett so will we. :-)

@abutaha thank you

**Comment by ChristophP** [comment]
@abutaha Friendly ping :-)

**Comment by abutaha** [comment]
Merged. Thanks!

**Comment by ChristophP** [comment]
Awesome, thank you :-)

**Pull request merged**
