### PR TITLE
Added support for assuming a role that has access to ElasticSearch

### PR DESCRIPTION
**Pull request by joshgarnett**
This replaces the #47 pull request.  It works with the latest changes to master.

### CODE REVIEW

**Comment by abutaha** [comment]
Thanks. Will merge this today.

**Comment by joshgarnett** [comment]
Thanks @abutaha let me know if you need any revisions.

**Comment by abutaha** [comment]
Hi, apologies for the delay in merging this. I took some time off the past few weeks. 
I see some conflicts caused by merging another PR. I will review this and get it merged later on this week.

**Comment by joshgarnett** [comment]
No worries.  If you don't have time let me know and I can look at resolving the conflicts.

**Comment by abutaha** [comment]
> No worries. If you don't have time let me know and I can look at resolving the conflicts.

Can I bother you and ask to please do that? I've backlog to look at work and a very demanding customer consuming my time. I don't want to delay this more, so the second the conflicts are fixed I will merge them.

thanks in advance!

**Comment by ChristophP** [comment]
We just ran into as well because we want to have `aws-es-proxy` assume a role. Would be great to have this.

**Comment by joshgarnett** [comment]
Replaced by #85 closing

**Pull request closed without merging**
