### PR TITLE
Added support for assuming a role that has access to ElasticSearch

### PR DESCRIPTION
**Pull request by joshgarnett**
* A user can now optionally pass in -assume and a role arn.  This role arn will be assumed before attempting to sign the the ElasticSearch request
* Fixed an issue where a 403 would result in a 200 being returned to the client hitting the proxy
* Moved a number of Fatalln calls to Println as Fatalln causes the process to panic, which is not the desired behavior.

### CODE REVIEW

**Comment by abutaha** [comment]
Hi, thanks for the patch. Will review and merge soon.

**Comment by abutaha** [comment]
Thanks for this patch. I'm playing with it on a local branch and will have it merged in v1.0-dev sometime this week.

I need some help fixing Kibana blank page on recent versions of ES, I'll be grateful if you can give me a hand on that.

**Comment by joshgarnett** [comment]
@abutaha I haven't hit a blank page issue with Kibana.  I've just been using the managed ElasticSearch option and it's worked out of the box.

**Comment by abutaha** [comment]
@joshgarnett if possible, launch a cluster using version 6.5, then access kibana through the proxy, the result is a 403 and a blank page. 

{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

starting the proxy on an older ES version like 6.2 work out of the box.

It seems there's a change in IAM on the AWS side starting with ES version 6.5+. I'm not able to find yet what has changed, but from the error message, the request don't reach Kibana at all and stops at the IAM authentication level.

**Comment by markhughes** [comment]
@abutaha is this still on the table?

**Comment by sc250024** [comment]
Nice! Any way we can get this merged? Is this project still being maintained?

**Pull request closed without merging**
